FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install -U pip

RUN pip install pipenv

COPY [ "Pipfile", "Pipfile.lock", "./" ]

RUN pipenv install --system --deploy
RUN pip install --no-cache-dir pandas numpy scikit-learn pyarrow

COPY [ "script_cli.py", "script_cli.py" ]

ENTRYPOINT [ "python", "script_cli.py", "2023", "5" ]


