services:

  postgres:
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      
      networks:
        - astro_airflow
      volumes:
        - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - astro_airflow
    
    
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    extra_hosts:      
       - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - astro_airflow
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
      

  mlflow:
    image: ghcr.io/mlflow/mlflow
    # command: >
    #   bash -c "pip install boto3 &&
    #            mlflow server
    #            --host 0.0.0.0
    #            --backend-store-uri sqlite:////data/mlflow_backend.db
    #            --default-artifact-root s3://mlflowdata"
    command: bash -c '(pip install -q boto3) && (mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////data/mlflow_backend.db --default-artifact-root s3://mlflowdata)'
    
    ports:
      - "5000:5000"
    volumes:
      - ./include/mlflow:/data
    networks:
      - astro_airflow
    depends_on:
      - minio
    restart: always

  # airflow:
  #     environment:
  #       - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  #       - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  #     env_file:
  #       - .env


volumes:
  minio-data:
  pgadmin-data:
  postgres_data:
    driver: local

networks:
  astro_airflow:
    driver: bridge
    attachable: true
    name: astro_airflow
    external: true

